### ISSUE TITLE
Connector types are not matching

### ISSUE THREAD

**Issue by vctrmn** [camunda/connector-template#23]
__Describe the Bug__

The OutboundConnector type of `MyConnectorFunction.java` is not matching the `template-connector.json` type

**Comment by vctrmn** [comment]
Assign to me, I will make a PR tomorrow

**Comment by tmetzke** [comment]
Hi @vctrmn,

thanks a lot for noticing! I fixed this with https://github.com/camunda/connector-template/commit/d1bc1a6ad455bff3aeea84d7c09087a35c2c3e11.
